# fly.toml app configuration file generated for umbraco23 on 2023-10-12T10:45:29+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "umbraco23"
primary_region = "mad"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
